### ISSUE TITLE
Sorular

### ISSUE THREAD

**Issue by ozank** [odtu/ee564#5]
Merhaba arkadaslar,
Github kullanımı veya transformer tasarımı hakkındaki sorularınızı burda yeni issue açıp sorabilirsiniz.

**Comment by Sedakl** [comment]
Hocam geçen ki proje de klasörü siz oluşturmuştunuz ben yine klasör oluşturamıyorum :(

**Comment by ozank** [comment]
Selam Seda,

Github boş klasör oluşturmaya izin vermiyor. Klasörün içinde bir dosya koyup oluşturabilirsin. README.md dosyası koyarsan, web sayfasında bir açıklama da gösterebilirsin
